version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    branches:
      only:
        - master
        - spike_pypi
    steps:
      - checkout
      - run:
          name: Get required packages
          command: apt-get update && apt-get install -y git python3 python3-pip
      - run:
          name: Install python-sphinx
          command: echo "13\n1\n" | apt-get install
      - run:
          name: Install pip package dependency
          command: pip3 install -r requirements.txt
      - run:
          name: Download Blender Source
          command: git clone git://git.blender.org/blender.git
      - run:
          name: Download all Blender
          command: bash tools/utils/download_blender.sh all blender-bin
      - run:
          name: Make build directory
          command: mkdir build
      - run:
          name: Generate pip Packages (Blender 2.78)
          command: bash tools/pip_package/build_pip_package.sh release 2.78 blender blender-bin/blender-v278-bin/blender-2.78-windows64 && mv tools/pip_package/release/dist
      - store_artifacts:
          path: tools/pip_package/build
          destination: fake-bpy-module-2.78