version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    environment:
      DEBIAN_FRONTEND: noninteractive
    branches:
      only:
        - master
        - spike_pypi
    steps:
      - checkout
      - run:
          name: Get required packages
          command: apt-get update && apt-get install -y git python3 python3-pip python-sphinx curl unzip blender
      - run:
          name: Install pip package dependency
          command: pip3 install -r requirements.txt
      - run:
          name: Install pip package 'pathlib'
          command: pip3 install pathlib
      - run:
          name: Download Blender Source
          command: git clone git://git.blender.org/blender.git
      - run:
          name: Download all Blender
          command: bash tools/utils/download_blender.sh all blender-bin
      - run:
          name: Make build directory
          command: mkdir build
      - run:
          name: Generate pip Packages (Blender 2.78)
          command: bash tools/pip_package/build_pip_package.sh release 2.78 blender blender-bin/blender-v278-bin
      - store_artifacts:
          path: release
          destination: fake-bpy-module-2.78